repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: ''
    hooks:
    -   id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: "v0.782"
#    hooks:
#    - id: mypy
